### ISSUE TITLE
Proposal: move nouns array to global scope

### ISSUE THREAD

**Issue by jessehcode** [slifty/internet_noise#19]
#### Move nouns array to global scope

Basic rationale for this is to make the nouns array easily accessible to console and manually injected scripts. Very simple change, which I am ready to open a PR for given the appropriate permissions. This will allow more technically inclined users to augment the collection of nouns.

**Comment by slifty** [comment]
Sounds like a fine plan to me especially for the short term -- you shouldn't need permissions to issue a PR!  Just send it over and I'll check it out.

**Comment by jessehcode** [comment]
Oddly enough, it gives me a 403 when I try to publish a branch. I'm executing `git push --set-upstream origin global-noun-array`. 

Regardless, I've attached the modified repo for your review.
[internet_noise.zip](https://github.com/slifty/internet_noise/files/884527/internet_noise.zip)

**Comment by slifty** [comment]
Ah is it possible you are working directly with this repo instead of a forked copy? If you fork your own copy and set your upstream to THAT you should be in good shape (edit .git/config and swap out the URL for your version).  From there you would use github's interface to make the pull request.  (I'd rather do it that way in the spirit of commit history!)

**Comment by jessehcode** [comment]
Yesterday was a long day (or at least, that's the excuse I'm going with for such a simple goof 😁). The pull request can be found here: https://github.com/slifty/internet_noise/pull/22.

**Comment by jessehcode** [comment]
Thanks! Closing the issue (merge https://github.com/slifty/internet_noise/pull/22).

**Comment by slifty** [comment]
Absolutely!  And thank you for the contribution and idea (also no excuse needed -- goofs are nothing to be ashamed of!)
