### ISSUE TITLE
Under some circumstances more than five tabs are opened at a time.

### ISSUE THREAD

**Issue by slifty** [slifty/internet_noise#3]
I'm trying to replicate the bug.  It appears if you leave this running over time far more than 5 tabs will end up being used.

At the very least it would be good to be able to detect when this has happened and close the old tab.  Ideally an extra tab would never be opened in the first place.

**Comment by slifty** [comment]
cc @Prinzhorn on the off chance this rings any bells; I'll keep snooping in the mean time.

**Comment by slifty** [comment]
This has been resolved; using .location instead of .open did the trick.

**Comment by Prinzhorn** [comment]
Ah great. I originally wanted to cache the popups as well but my (limited) tested worked anyway.
